version: "3.12"

services:
  memcached:
    image: memcached:1.6.23-alpine
    container_name: memcached
    ports:
      - "11211:11211"

  rabbitmq:
    image: rabbitmq:3.12.12-management-alpine
    container_name: rabbitmq
    env_file: .env
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres:
    image: postgres:15.6-alpine
    container_name: postgres
    env_file: .env
    ports:
      - '5432:5432'