# Generated by Django 4.2.7 on 2023-12-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Name')),
                ('email_from', models.EmailField(max_length=128, verbose_name='E-mail From')),
                ('subject', models.CharField(max_length=256, verbose_name='Subject')),
                ('body', models.CharField(blank=True, max_length=250, null=True, verbose_name='Body')),
            ],
            options={
                'verbose_name': 'Contact Us',
                'verbose_name_plural': 'Contact Us',
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Buy')),
                ('sell', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Sell')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('currency_type', models.SmallIntegerField(choices=[(1, 'USD'), (2, 'EUR')], default=1,
                                                           verbose_name='Currency Type')),
                ('source', models.CharField(max_length=255, verbose_name='Source')),
            ],
            options={
                'verbose_name': 'Rate',
                'verbose_name_plural': 'Rates',
            },
        ),
        migrations.CreateModel(
            name='RequestResponseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('path', models.CharField(max_length=255, verbose_name='Path')),
                ('request_method', models.CharField(max_length=10, verbose_name='Request Method')),
                ('time', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Response Time')),
            ],
            options={
                'verbose_name': 'Request Response Log',
                'verbose_name_plural': 'Request Response Logs',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(max_length=255, verbose_name='Source Url')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
            ],
        ),
    ]
