# Generated by Django 4.2.7 on 2023-12-06 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='body',
            field=models.CharField(max_length=250, null=True, verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='name',
            field=models.CharField(max_length=64, null=True, verbose_name='Name'),
        ),
    ]
