# Generated by Django 4.2.7 on 2023-12-22 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='source',
            options={'verbose_name': 'Source', 'verbose_name_plural': 'Sources'},
        ),
        migrations.AddField(
            model_name='source',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='sources/', verbose_name='Logo'),
        ),
    ]
