# Generated by Django 4.2.7 on 2023-11-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0005_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
