# Generated by Django 4.2.7 on 2023-11-27 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0006_source_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
