# Generated by Django 4.2.7 on 2023-12-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0008_contactus_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='currency_type',
            field=models.SmallIntegerField(choices=[(1, 'USD'), (2, 'EUR')], default=1),
        ),
    ]
