# Generated by Django 4.2.7 on 2023-12-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0011_alter_contactus_options_alter_rate_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='message',
        ),
        migrations.AddField(
            model_name='contactus',
            name='body',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Body'),
        ),
        migrations.AddField(
            model_name='contactus',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='email_from',
            field=models.EmailField(max_length=128, verbose_name='E-mail From'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='subject',
            field=models.CharField(max_length=256, verbose_name='Subject'),
        ),
    ]
